[package]
name = "birthday-paradox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fake = { version = "2.5.0", features = ["derive"] }
indicatif = "0.17.1"
rand = "0.8.5"
